# Generated by Django 4.0.5 on 2022-06-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
