# Generated by Django 4.0.5 on 2022-06-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_github_user_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='https://www.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png', upload_to='profiles/'),
        ),
    ]
