# Generated by Django 4.0.5 on 2022-06-12 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_author_alter_question_body'),
        ('users', '0006_alter_user_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.category'),
        ),
    ]
