# Generated by Django 4.0.5 on 2022-06-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='body',
        ),
    ]
