# Generated by Django 4.0.5 on 2022-06-10 05:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_question_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
