# Generated by Django 4.0.5 on 2022-06-09 06:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
