# Generated by Django 4.0.5 on 2022-06-10 05:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_alter_answer_author_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
